module.exports = {
  darkMode: 'class',
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        lmtext: "var(--lmtext)",
        lmbutton: "var(--lmbutton)",
        lmbuttonhover: "var(--lmbuttonhover)",
        lmbackground: "var(--lmbackground)",
        lmnavbg: "var(--lmnavbg)",
        dmtext: "var(--dmtext)",
        dmbutton: "var(--dmbutton)",
        dmbuttonhover: "var(--dmbuttonhover)",
        dmbackground: "var(--dmbackground)",
        dmnavbg: "var(--dmnavbg)",
        dracbg: "var(--dracbg)",
        draccurline: "var(--draccurline)",
        dracfg: "var(--dracfg)",
        draccomment: "var(--draccomment)",
        draccyan: "var(--draccyan)",
        dracgreen: "var(--dracgreen)",
        dracorange: "var(--dragorgance)",
        dracpink: "var(--dracpink)",
        dracpurple: "var(--dracpurple)",
        dracred: "var(--dracred)",
        dracyellow: "var(--dracyellow)",
        // primary: "var(--primary)",
        // secondary: "var(--secondary)",
        // main: "var(--main)",
        // header: "var(--header)",
        // accent: "var(--accent)",
      },
      spacing: {
        '120': '30rem',
        '140': '35rem',
      },
    },
  },
  plugins: [],
}
